setenv(HARDWARE_LIB = $SIGNED_CYCLONE3)
setenv(DESIGN_LATENCY = 5000)
setenv(CST_ALLOCATION = constraints\resources)
setenv(CST_DATE = constraints\IODate)
setenv(CST_PORTS = constraints\IOPort)

MatlabAnalyser(Model.m)
hls_OptimizeGraph($RESSOURCES/arithmetic/reduce_computation.xml)
dyn_SetInputBitwise(8,1)
dyn_ComputeDynamique
dyn_ComputeBitwise
dyn_LimitBitwise(32)

contracts-init
contracts-preprocess
contracts-tag
contracts-prepare
contracts-pull

contracts-debug-env